// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var copy, downloadFile, fs, validate;
  fs = require('fs');
  copy = require('fs.extra').copy;
  downloadFile = require('../download');
  validate = require('../checksum');
  module.exports = function (binPath, tempPath, url, version, callback) {
    var binFilePath, file, tempFileName, tempFilePath;
    file = 'selenium.jar';
    binFilePath = '' + binPath + '/' + file;
    if (fs.existsSync(binFilePath))
      return callback();
    tempFileName = 'selenium_' + version + '.jar';
    tempFilePath = '' + tempPath + '/' + tempFileName;
    if (fs.existsSync(tempFilePath)) {
      return copy(tempFilePath, binFilePath, callback);
    } else {
      return downloadFile(url, tempPath, tempFileName, function (error, hash) {
        if (null != error)
          return callback(error);
        return validate(tempFilePath, hash, function (error) {
          if (null != error)
            return callback(error);
          return copy(tempFilePath, binFilePath, callback);
        });
      });
    }
  };
}.call(this);
