// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var createHash, fs;
  fs = require('fs');
  createHash = require('crypto').createHash;
  module.exports = function (filePath, checksum, callback) {
    var hash, stream;
    hash = createHash('md5');
    stream = fs.ReadStream(filePath);
    stream.on('data', function (data) {
      return hash.update(data);
    });
    return stream.on('end', function () {
      var digest, message;
      digest = hash.digest('base64');
      if (digest !== checksum) {
        message = 'File ' + filePath + ' did not match checksum: expected ' + checksum + ' but saw ' + digest;
        return callback(new Error(message));
      }
      return callback();
    });
  };
}.call(this);
