// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var download, parseHashes;
  download = require('download');
  parseHashes = function (rawHash) {
    var hashes, parse;
    parse = function (result, hash) {
      var key, parts, value;
      parts = hash.trim().split('=');
      key = parts[0];
      value = parts.splice(1).join('=');
      result[key] = value;
      return result;
    };
    hashes = rawHash.split(',');
    return hashes.reduce(parse, {});
  };
  module.exports = function (url, destinationDir, fileName, callback) {
    var fileOptions, hash, stream;
    hash = null;
    fileOptions = {
      url: url,
      name: fileName
    };
    stream = download(fileOptions, destinationDir);
    stream.on('response', function (response) {
      var rawHash;
      rawHash = response.headers['x-goog-hash'];
      return hash = parseHashes(rawHash).md5;
    });
    stream.on('error', function (error) {
      return callback(error);
    });
    return stream.on('close', function () {
      return callback(null, hash);
    });
  };
}.call(this);
