// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var async, binariesExist, ensure, ensureChromedriver, ensureSelenium, existsSync, forceUpdate, makePaths, mkdirp, removeDir, rmrfSync, TEMP_PATH, tempdir, update;
  existsSync = require('fs').existsSync;
  rmrfSync = require('fs.extra').rmrfSync;
  mkdirp = require('mkdirp');
  async = require('async');
  tempdir = require('./tempdir');
  ensureSelenium = require('./selenium');
  ensureChromedriver = require('./chromedriver');
  TEMP_PATH = '' + tempdir + 'testium';
  makePaths = function (binPath, tempPath) {
    mkdirp.sync(binPath);
    return mkdirp.sync(tempPath);
  };
  removeDir = function (dir) {
    return rmrfSync(dir);
  };
  binariesExist = function (binPath) {
    return [
      'selenium.jar',
      'chromedriver'
    ].every(function (binary) {
      return existsSync('' + binPath + '/' + binary);
    });
  };
  ensure = function (binPath, callback) {
    if (binariesExist(binPath))
      return callback();
    makePaths(binPath, TEMP_PATH);
    return async.parallel([
      ensureSelenium(binPath, TEMP_PATH),
      ensureChromedriver(binPath, TEMP_PATH)
    ], callback);
  };
  update = function (binPath, callback) {
    removeDir(binPath);
    return ensure(binPath, callback);
  };
  forceUpdate = function (binPath, callback) {
    removeDir(binPath);
    removeDir(TEMP_PATH);
    return ensure(binPath, callback);
  };
  module.exports = {
    update: update,
    forceUpdate: forceUpdate,
    ensure: ensure
  };
}.call(this);
