// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var async, binariesExist, cache$, ensure, ensureChromedriver, ensureSelenium, existsSync, makePaths, mkdirp, removeFile, TEMP_PATH, tempdir, unlinkSync, update;
  cache$ = require('fs');
  unlinkSync = cache$.unlinkSync;
  existsSync = cache$.existsSync;
  mkdirp = require('mkdirp');
  async = require('async');
  tempdir = require('./tempdir');
  ensureSelenium = require('./selenium');
  ensureChromedriver = require('./chromedriver');
  TEMP_PATH = '' + tempdir + 'testium';
  makePaths = function (binPath, tempPath) {
    mkdirp.sync(binPath);
    return mkdirp.sync(tempPath);
  };
  removeFile = function (file) {
    if (existsSync(file))
      return unlinkSync(file);
  };
  binariesExist = function (binPath) {
    return [
      'selenium.jar',
      'chromedriver'
    ].every(function (binary) {
      return existsSync('' + binPath + '/' + binary);
    });
  };
  ensure = function (binPath, callback) {
    if (binariesExist(binPath))
      return callback();
    makePaths(binPath, TEMP_PATH);
    return async.parallel([
      ensureSelenium(binPath, TEMP_PATH),
      ensureChromedriver(binPath, TEMP_PATH)
    ], callback);
  };
  update = function (binPath, callback) {
    removeFile('' + binPath + '/selenium.jar');
    removeFile('' + binPath + '/chromedriver');
    return ensure(binPath, callback);
  };
  module.exports = {
    update: update,
    ensure: ensure
  };
}.call(this);
