// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var defaultTemp, normalize, temp;
  normalize = function (path) {
    var last;
    last = path[path.length - 1];
    if (process.platform !== 'win32') {
      if (last !== '/') {
        path += '/';
      }
    } else {
      path += '/';
    }
    return path;
  };
  defaultTemp = process.platform === 'win32' ? 'c:\\windows\\temp\\' : '/tmp/';
  temp = process.env.TMPDIR || process.env.TMP || process.env.TEMP || defaultTemp;
  module.exports = normalize(temp);
}.call(this);
