// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var AdmZip, async, cache$, copy, downloadFile, fs, move, unzip, validate;
  fs = require('fs');
  async = require('async');
  cache$ = require('fs.extra');
  copy = cache$.copy;
  move = cache$.move;
  AdmZip = require('adm-zip');
  downloadFile = require('../download');
  validate = require('../checksum');
  unzip = function (tempPath, filePath, callback) {
    var tempFilePath;
    tempFilePath = '' + filePath + '.tmp';
    return move(filePath, tempFilePath, function (error) {
      var zip;
      if (null != error)
        return callback(error);
      zip = new AdmZip(tempFilePath);
      zip.extractAllTo(tempPath);
      fs.unlinkSync(tempFilePath);
      return callback();
    });
  };
  module.exports = function (binPath, tempPath, version, url, callback) {
    var chromedriverPath, tempFileName, tempFilePath, unzippedFilePath;
    chromedriverPath = '' + binPath + '/chromedriver';
    if (fs.existsSync(chromedriverPath))
      return callback();
    tempFileName = 'chromedriver_' + version;
    tempFilePath = '' + tempPath + '/' + tempFileName;
    if (fs.existsSync(tempFilePath)) {
      return copy(tempFilePath, chromedriverPath, function (error) {
        if (null != error)
          return callback(error);
        return fs.chmod(chromedriverPath, '755', callback);
      });
    } else {
      unzippedFilePath = '' + tempPath + '/chromedriver';
      return async.waterfall([
        function (done) {
          return downloadFile(url, tempPath, tempFileName, 'selenium chromedriver ' + version, done);
        },
        function (hash, done) {
          return validate(tempFilePath, hash, done);
        },
        function (done) {
          return unzip(tempPath, tempFilePath, done);
        },
        function (done) {
          return move(unzippedFilePath, tempFilePath, done);
        },
        function (done) {
          return copy(tempFilePath, chromedriverPath, done);
        },
        function (done) {
          return fs.chmod(chromedriverPath, '755', done);
        }
      ], callback);
    }
  };
}.call(this);
