// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var download, getLatestVersion;
  download = require('./download');
  getLatestVersion = require('./version');
  module.exports = function (binPath, tempPath) {
    return function (callback) {
      return getLatestVersion(function (error, metadata) {
        if (null != error)
          return callback(error);
        return download(binPath, tempPath, metadata.version, metadata.downloadUrl, callback);
      });
    };
  };
}.call(this);
